# @name get-prompts

GET http://localhost:3333/promps

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

------X-INSOMNIA-BOUNDARY
Content-Disposition: form-data; name="file"; filename="chimes-7035.mp3"
Content-Type: audio/mpeg

./chimes-7035.mp3
------X-INSOMNIA-BOUNDARY--

###

# @name create-transcription

POST http://localhost:3333/videos/65f5e664-2f7f-4bad-b9b6-f3396314f0ef/transcription
Content-Type: application/json
{
    "prompt": "vídeo jornalístico sobre brasileiro foragido"
}

###

# @name ai-complete
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "65f5e664-2f7f-4bad-b9b6-f3396314f0ef",
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
